/* Isabela Martins v24 • Florindo Sistemas */
(function(){
'use strict';
const old={ass:renderAssessments,pat:renderPatientDetail,vis:renderVisits,fin:renderFinance,card:assessmentCard};
const INFO={chair:{name:'Sentar e levantar • 30 s',unit:'repetições',icon:'↕'},tug:{name:'Timed Up and Go • TUG',unit:'segundos',icon:'⏱'},berg:{name:'Escala de Equilíbrio de Berg',unit:'pontos',icon:'◒'}};
const BERG=['Sentar sem apoio','Sentado para em pé','Em pé para sentado','Transferências','Permanecer em pé sem apoio','Permanecer em pé com olhos fechados','Permanecer em pé com os pés juntos','Posição tandem','Permanecer em apoio unipodal','Olhar para trás sobre os ombros','Pegar objeto no chão','Girar 360 graus','Alternar os pés em um degrau','Alcançar à frente com o braço estendido'];
const NORMS={'60-64':{Masculino:14,Feminino:12},'65-69':{Masculino:12,Feminino:11},'70-74':{Masculino:12,Feminino:10},'75-79':{Masculino:11,Feminino:10},'80-84':{Masculino:10,Feminino:9},'85-89':{Masculino:8,Feminino:8},'90-94':{Masculino:7,Feminino:4}};
let edit='',type='chair',finView='geral',finMonth=today().slice(0,7),finYear=new Date().getFullYear(),repMonth=today().slice(0,7),repPatient='';
const E=v=>esc(v==null?'':v),N=v=>Number(v)||0;
function age(p,d=today()){if(!p?.birth)return'';let b=parseDate(p.birth),x=parseDate(d),a=x.getFullYear()-b.getFullYear();if(x.getMonth()<b.getMonth()||(x.getMonth()==b.getMonth()&&x.getDate()<b.getDate()))a--;return a>=0?a:''}
function rec(pid='',t=''){return assessments.filter(a=>a.functionalTest&&(!pid||a.patientId===pid)&&(!t||a.functionalTest.type===t)).sort((a,b)=>(a.date||'').localeCompare(b.date||''))}
function val(a){let f=a.functionalTest;return f.type==='chair'?N(f.reps):f.type==='tug'?N(f.seconds):N(f.score)}
function interp(f){if(f.type==='tug')return f.seconds>=12?['Atenção • ≥ 12 s','risk','Referência CDC STEADI: 12 s ou mais sinaliza risco aumentado de queda em adultos mais velhos.']:['< 12 s','ok','Abaixo do ponto de corte de triagem do CDC STEADI.'];if(f.type==='berg')return f.score<=20?['0–20 pontos','risk','Faixa de referência de maior dependência funcional.']:f.score<=40?['21–40 pontos','watch','Faixa associada à marcha com assistência.']:['41–56 pontos','ok','Faixa associada a maior independência funcional.'];if(f.arms)return['Teste interrompido • 0','risk','No protocolo STEADI, uso dos braços para levantar interrompe o teste e registra 0.'];let band=Object.keys(NORMS).find(k=>{let z=k.split('-').map(Number);return f.age>=z[0]&&f.age<=z[1]}),cut=NORMS[band]?.[f.sex];if(!cut)return['Resultado registrado','neutral','Sem ponto de corte disponível para esta idade/sexo.'];return f.reps<cut?['Abaixo da média','risk',`STEADI ${band} anos: abaixo de ${cut} repetições.`]:['Dentro/acima da referência','ok',`STEADI ${band} anos: ${cut} ou mais repetições.`]}
function css(){if(document.getElementById('v24css'))return;let s=document.createElement('style');s.id='v24css';s.textContent=`
.ftHero{padding:20px;border:1px solid #d8e0d1;border-radius:22px;background:linear-gradient(120deg,#fffaf0,#edf3e8);margin-bottom:15px}.ftHero h2{margin:0;color:#40583a;font:22px Georgia}.ftHero p{font-size:10px;color:#74806d}.ftGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ftCard,.ftChart{background:#fffefa;border:1px solid #dce4d5;border-radius:18px;padding:14px;box-shadow:0 9px 24px #26351c0b}.ftCard h3,.ftChart h3{margin:0 0 5px;color:#40583a;font-size:13px}.ftCard p{font-size:9px;color:#7c8675;min-height:30px}.ftValue{font-size:21px;font-weight:900;color:#4d6846;margin:8px 0}.ftRef{padding:9px;border-radius:11px;font-size:9px;line-height:1.45;margin:8px 0}.ftRef.ok{background:#edf6e9;color:#496847}.ftRef.risk{background:#faece8;color:#8c5045}.ftRef.watch{background:#f9f1df;color:#81683a}.ftRef.neutral{background:#f1f3ed;color:#6c7767}.ftBerg{display:grid;gap:6px}.ftBergRow{display:grid;grid-template-columns:26px 1fr 90px;align-items:center;gap:7px;padding:7px;border:1px solid #e3e8dd;border-radius:10px;background:#fafbf6;font-size:9px}.ftBergRow b{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:#e5ede0}.ftChart{margin-top:10px}.ftChart svg{width:100%;height:190px}.ftChart line{stroke:#e3e8de}.ftChart polyline{fill:none;stroke:#799172;stroke-width:3}.ftChart circle{fill:#c6a15a;stroke:#fff;stroke-width:2}.ftChart text{font:9px system-ui;fill:#788273}.ftTabs{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 13px}.ftTabs button{border:1px solid #d5dece;background:#fffefa;color:#596d52;border-radius:999px;padding:8px 11px;font-size:9px;font-weight:800}.ftTabs button.active{background:#536c4b;color:#fff}.ftReport{margin:13px 0}.ftReportBar{display:flex;gap:7px;flex-wrap:wrap}.ftReportBar input,.ftReportBar select{width:auto}.ftMonthRow{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid #e6eadf;padding:9px 2px;font-size:10px}.ftAnnual{display:grid;grid-template-columns:repeat(12,minmax(38px,1fr));gap:5px;align-items:end;height:190px;overflow-x:auto;padding-bottom:22px}.ftCol{height:150px;display:flex;align-items:flex-end;justify-content:center;gap:2px;position:relative}.ftBar{width:42%;background:#7e9677;border-radius:5px 5px 0 0;min-height:2px}.ftBar.out{background:#c4a56a}.ftCol span{position:absolute;bottom:-18px;font-size:7px}.ftFunctionalTab{font-weight:800!important}@media(max-width:700px){.ftGrid{grid-template-columns:1fr}.ftBergRow{grid-template-columns:25px 1fr 78px}.ftReportBar>*{width:100%!important}}
@media print{.ftNoPrint{display:none!important}}`;document.head.appendChild(s)}
function modal(){if(document.getElementById('ftModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="ftModal"><div class="modal"><div class="modal-head"><h3 id="ftTitle">Teste funcional</h3><button class="btn tiny" onclick="closeModal('ftModal')">✕</button></div><div class="modal-body" id="ftBody"></div><div class="modal-foot"><button class="btn" onclick="closeModal('ftModal')">Cancelar</button><button class="btn primary" onclick="ftSave()">Salvar teste</button></div></div></div><div class="modal-back" id="ftRepModal"><div class="modal"><div class="modal-head"><h3>Relatório mensal</h3><button class="btn tiny" onclick="closeModal('ftRepModal')">✕</button></div><div class="modal-body" id="ftRepBody"></div><div class="modal-foot"><button class="btn" onclick="window.print()">Imprimir / PDF</button><button class="btn primary" onclick="closeModal('ftRepModal')">Fechar</button></div></div></div>`)}
function hero(pid=''){return `<section class="ftHero"><h2>Testes funcionais</h2><p>Acompanhe evolução com medidas repetidas e gráfico individual. Referências são apoio ao raciocínio clínico, não diagnóstico isolado.</p><div class="ftGrid">${Object.keys(INFO).map(t=>{let a=rec(pid,t),last=a.at(-1);return `<div class="ftCard"><h3>${INFO[t].icon} ${INFO[t].name}</h3><p>${t==='chair'?'Força e resistência de membros inferiores em 30 segundos.':t==='tug'?'Mobilidade funcional em percurso de 3 metros.':'Equilíbrio funcional em 14 tarefas (0–56).'} </p><div class="ftValue">${last?val(last)+' '+INFO[t].unit:'—'}</div><button class="btn primary tiny" onclick="ftOpen('${t}','${pid}')">+ Aplicar teste</button></div>`}).join('')}</div></section>`}
function open(t='chair',pid='',id=''){modal();type=t;edit=id;let a=id?assessments.find(x=>x.id===id):null;if(a){type=a.functionalTest.type;pid=a.patientId}pid=pid||selectedPatientId||patients[0]?.id||'';let p=patientById(pid),d=a?.date||today(),f=a?.functionalTest||{},ag=f.age??age(p,d),specific='';
if(type==='chair')specific=`<div class="field"><label>Sexo para referência</label><select id="ftSex"><option></option><option ${f.sex==='Feminino'?'selected':''}>Feminino</option><option ${f.sex==='Masculino'?'selected':''}>Masculino</option></select></div><div class="field"><label>Nº de vezes que conseguiu</label><input id="ftReps" type="number" min="0" value="${E(f.rawReps??f.reps??'')}"></div><div class="field full"><label><input id="ftArms" type="checkbox" style="width:auto" ${f.arms?'checked':''}> Precisou usar os braços</label></div>`;
else if(type==='tug')specific=`<div class="field"><label>Tempo total (segundos)</label><input id="ftSeconds" type="number" min="0" step="0.1" value="${E(f.seconds??'')}"></div><div class="field"><label>Auxílio</label><select id="ftAid"><option></option>${['Bengala','Andador','Muletas','Outro'].map(v=>`<option ${f.aid===v?'selected':''}>${v}</option>`).join('')}</select></div>`;
else{let scores=f.items||Array(14).fill('');specific=`<div class="field full"><div class="ftBerg">${BERG.map((x,i)=>`<div class="ftBergRow"><b>${i+1}</b><span>${x}</span><select class="ftScore"><option value=""></option>${[0,1,2,3,4].map(v=>`<option value="${v}" ${scores[i]!==''&&Number(scores[i])===v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}</div></div>`}
document.getElementById('ftTitle').textContent=(a?'Editar • ':'Novo • ')+INFO[type].name;document.getElementById('ftBody').innerHTML=`<div class="form-grid"><div class="field"><label>Paciente</label><select id="ftPatient">${patients.map(x=>`<option value="${x.id}" ${x.id===pid?'selected':''}>${E(x.name)}</option>`).join('')}</select></div><div class="field"><label>Data</label><input id="ftDate" type="date" value="${d}"></div><div class="field"><label>Idade</label><input id="ftAgeInput" type="number" min="0" max="120" value="${E(ag)}"></div>${specific}<div class="field full"><label>Observações</label><textarea id="ftNotes">${E(f.notes||'')}</textarea></div><div class="field full" id="ftPreview"></div></div>`;document.querySelectorAll('#ftBody input,#ftBody select').forEach(x=>x.addEventListener('input',preview));document.getElementById('ftPatient').onchange=function(){let q=patientById(this.value);document.getElementById('ftAgeInput').value=age(q,document.getElementById('ftDate').value);preview()};openModal('ftModal');preview()}
window.ftOpen=open;
function preview(){let f={type,age:N(document.getElementById('ftAgeInput')?.value)};if(type==='chair'){f.sex=document.getElementById('ftSex')?.value||'';f.reps=N(document.getElementById('ftReps')?.value);f.arms=!!document.getElementById('ftArms')?.checked}else if(type==='tug')f.seconds=N(document.getElementById('ftSeconds')?.value);else{let v=[...document.querySelectorAll('.ftScore')].map(x=>x.value===''?null:Number(x.value));f.score=v.reduce((s,x)=>s+(x||0),0);if(v.some(x=>x===null)){document.getElementById('ftPreview').innerHTML=`<div class="ftRef neutral">${v.filter(x=>x!==null).length}/14 itens • ${f.score} pontos</div>`;return}}let q=interp(f);document.getElementById('ftPreview').innerHTML=`<div class="ftRef ${q[1]}"><b>${q[0]}</b><br>${q[2]}</div>`}
window.ftSave=async function(){let pid=document.getElementById('ftPatient').value,d=document.getElementById('ftDate').value,ageEl=document.getElementById('ftAgeInput'),ag=N(ageEl.value),notes=document.getElementById('ftNotes').value.trim();if(!pid||!d||ageEl.value==='')return alert('Informe paciente, data e idade.');let f={type,age:ag,notes};if(type==='chair'){let r=document.getElementById('ftReps'),sex=document.getElementById('ftSex').value,arms=document.getElementById('ftArms').checked;if(r.value===''||!sex)return alert('Informe sexo e número de repetições.');f.rawReps=N(r.value);f.reps=arms?0:N(r.value);f.arms=arms;f.sex=sex}else if(type==='tug'){let x=N(document.getElementById('ftSeconds').value);if(x<=0)return alert('Informe o tempo do TUG.');f.seconds=x;f.aid=document.getElementById('ftAid').value}else{f.items=[...document.querySelectorAll('.ftScore')].map(x=>x.value===''?null:Number(x.value));if(f.items.some(x=>x===null))return alert('Preencha os 14 itens da Berg.');f.score=f.items.reduce((s,x)=>s+x,0)}let q=interp(f);f.interpretation=q[0];let obj={patientId:pid,date:d,title:INFO[type].name,functionalTest:f,answers:{Idade:String(ag),Resultado:type==='tug'?f.seconds+' s':type==='berg'?f.score+'/56':f.reps+' repetições',Observações:notes},updatedAt:new Date().toISOString()};if(edit){let a=assessments.find(x=>x.id===edit);if(a)Object.assign(a,obj)}else assessments.push({id:uid(),createdAt:new Date().toISOString(),...obj});edit='';closeModal('ftModal');selectedPatientId=pid;patientTab='funcionais';currentPage='patients';await persist()};
function fcard(a){let f=a.functionalTest,q=interp(f);return `<div class="mini-card"><h3>${INFO[f.type].icon} ${INFO[f.type].name}</h3><p>${brDate(a.date)} • ${E(patientById(a.patientId)?.name||'')}</p><div class="ftValue">${val(a)} ${INFO[f.type].unit}</div><div class="ftRef ${q[1]}"><b>${q[0]}</b><br>${q[2]}</div>${f.notes?`<p><b>Obs.:</b> ${E(f.notes)}</p>`:''}<div class="actions"><button class="btn tiny" onclick="ftOpen('${f.type}','${a.patientId}','${a.id}')">Editar</button><button class="btn tiny red" onclick="deleteAssessment('${a.id}')">Excluir</button></div></div>`}
function chart(pid,t){let a=rec(pid,t);if(a.length<2)return `<div class="ftChart"><h3>${INFO[t].name}</h3><div class="empty" style="padding:25px">Aplique o teste duas vezes para gerar o gráfico.</div></div>`;let vs=a.map(val),min=Math.min(...vs),max=Math.max(...vs);if(min===max){min-=1;max+=1}let W=620,H=180,L=38,R=18,T=16,B=28,x=i=>L+(W-L-R)*(i/(a.length-1)),y=v=>T+(H-T-B)*(1-(v-min)/(max-min)),pts=vs.map((v,i)=>`${x(i)},${y(v)}`).join(' ');return `<div class="ftChart"><h3>${INFO[t].name} • evolução</h3><svg viewBox="0 0 ${W} ${H}"><line x1="${L}" y1="${H-B}" x2="${W-R}" y2="${H-B}"/><polyline points="${pts}"/>${a.map((r,i)=>`<circle cx="${x(i)}" cy="${y(vs[i])}" r="5"><title>${brDate(r.date)} • ${vs[i]} ${INFO[t].unit}</title></circle><text x="${x(i)}" y="${H-7}" text-anchor="middle">${String(r.date).slice(5)}</text>`).join('')}</svg></div>`}
function patientFunctional(pid){let a=rec(pid).slice().reverse();return hero(pid)+`<div class="panel-title"><h3>Histórico funcional</h3><span class="tag">${a.length} teste(s)</span></div><div class="cards">${a.length?a.map(fcard).join(''):'<div class="empty">Nenhum teste funcional aplicado.</div>'}</div>${Object.keys(INFO).map(t=>chart(pid,t)).join('')}`}
renderPatientDetail=function(){if(patientTab!=='funcionais'){old.pat();let tabs=document.querySelector('#main .tabs');if(tabs&&!tabs.querySelector('.ftFunctionalTab'))tabs.insertAdjacentHTML('beforeend',`<button class="ftFunctionalTab" onclick="patientTab='funcionais';render()">Testes funcionais</button>`);if(patientTab==='dados'){let p=patientById(selectedPatientId),birth=[...document.querySelectorAll('#main .info')].find(x=>x.textContent.trim().startsWith('Nascimento'));if(birth&&!document.querySelector('#main .ftAgeInfo'))birth.insertAdjacentHTML('afterend',`<div class="info ftAgeInfo"><label>Idade</label><div>${age(p)===''?'-':age(p)+' anos'}</div></div>`)}return}let wanted=patientTab;patientTab='avaliacoes';old.pat();patientTab=wanted;let panel=document.querySelector('#main .patient-shell .panel'),tabs=panel?.querySelector('.tabs');if(!panel||!tabs)return;tabs.querySelectorAll('button').forEach(b=>b.classList.remove('active'));tabs.insertAdjacentHTML('beforeend',`<button class="active ftFunctionalTab" onclick="patientTab='funcionais';render()">Testes funcionais</button>`);panel.innerHTML=tabs.outerHTML+patientFunctional(selectedPatientId)};window.renderPatientDetail=renderPatientDetail;
assessmentCard=function(a,full=false){return a?.functionalTest?fcard(a):old.card(a,full)};window.assessmentCard=assessmentCard;
renderAssessments=function(){old.ass();if(typeof evaluationWork!=='undefined'&&(evaluationWork||evaluationRead))return;let h=document.querySelector('#main .page-head');if(h&&!document.querySelector('#main .ftHero'))h.insertAdjacentHTML('afterend',hero())};window.renderAssessments=renderAssessments;
function monthly(){return appointments.filter(a=>a.date?.slice(0,7)===repMonth&&(!repPatient||a.patientId===repPatient)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}
function monthlyPanel(){let a=monthly(),real=a.filter(x=>x.status==='Realizado').length;return `<section class="ftHero ftReport"><h2>Relatório mensal de atendimentos</h2><p>Filtre por mês e paciente, visualize e baixe os atendimentos.</p><div class="ftReportBar"><input type="month" value="${repMonth}" onchange="ftRepMonth(this.value)"><select onchange="ftRepPatient(this.value)"><option value="">Todos os pacientes</option>${patients.map(p=>`<option value="${p.id}" ${p.id===repPatient?'selected':''}>${E(p.name)}</option>`).join('')}</select><button class="btn primary" onclick="ftOpenReport()">Gerar relatório</button><button class="btn green" onclick="ftDownloadReport()">⬇ Baixar CSV</button></div><div class="grid4" style="margin-top:12px"><div class="metric"><label>Total</label><b>${a.length}</b></div><div class="metric green"><label>Realizados</label><b>${real}</b></div><div class="metric orange"><label>Não realizados</label><b>${a.filter(x=>x.status==='Não realizado').length}</b></div><div class="metric red"><label>Cancelados</label><b>${a.filter(x=>x.status==='Cancelado').length}</b></div></div></section>`}
window.ftRepMonth=v=>{repMonth=v;render()};window.ftRepPatient=v=>{repPatient=v;render()};
renderVisits=function(){old.vis();let h=document.querySelector('#main .page-head');if(h)h.insertAdjacentHTML('afterend',monthlyPanel())};window.renderVisits=renderVisits;
window.ftOpenReport=function(){modal();let a=monthly(),groups={};a.forEach(x=>{let n=appointmentName(x);groups[n]=groups[n]||{n,total:0,real:0};groups[n].total++;if(x.status==='Realizado')groups[n].real++});document.getElementById('ftRepBody').innerHTML=`<div class="assessment-sheet"><h1>Relatório mensal de atendimentos</h1><p>${new Date(repMonth+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</p><div class="grid4">${[['Total',a.length],['Realizados',a.filter(x=>x.status==='Realizado').length],['Não realizados',a.filter(x=>x.status==='Não realizado').length],['Cancelados',a.filter(x=>x.status==='Cancelado').length]].map(x=>`<div class="metric"><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div><h3>Por paciente</h3>${Object.values(groups).map(g=>`<div class="ftMonthRow"><b>${E(g.n)}</b><span>${g.real} realizado(s) • ${g.total} total</span></div>`).join('')}<h3>Atendimentos</h3><div class="table-wrap"><table><thead><tr><th>Data</th><th>Paciente</th><th>Horário</th><th>Status</th><th>Valor</th></tr></thead><tbody>${a.map(x=>`<tr><td>${brDate(x.date)}</td><td>${E(appointmentName(x))}</td><td>${E(x.start||'')}</td><td>${E(x.status||'')}</td><td>${brMoney(x.value)}</td></tr>`).join('')}</tbody></table></div></div>`;openModal('ftRepModal')};
window.ftDownloadReport=function(){let a=monthly(),csv=['Data;Paciente;Início;Fim;Status;Valor;Pagamento;Observações',...a.map(x=>[brDate(x.date),appointmentName(x),x.start||'',x.end||'',x.status||'',x.value||0,paymentStatus(x),String(x.note||'').replace(/;/g,',')].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';'))].join('\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`atendimentos_${repMonth}.csv`)};
function period(start,end){let a=finance.filter(f=>{let d=f.paidDate||f.dueDate||'';return d>=start&&d<=end}),paid=a.filter(f=>f.status==='Pago'),inn=paid.filter(f=>f.direction==='Entrada').reduce((s,f)=>s+N(f.value),0),out=paid.filter(f=>f.direction==='Saída').reduce((s,f)=>s+N(f.value),0);return{a,inn,out,bal:inn-out,pend:a.filter(f=>f.status!=='Pago').reduce((s,f)=>s+N(f.value),0)}}
function tabs(){return `<div class="ftTabs"><button class="${finView==='geral'?'active':''}" onclick="ftFin('geral')">Geral</button><button class="${finView==='mes'?'active':''}" onclick="ftFin('mes')">Balanço mensal</button><button class="${finView==='ano'?'active':''}" onclick="ftFin('ano')">Balanço anual</button></div>`}window.ftFin=v=>{finView=v;renderFinance()};window.ftFinMonth=v=>{finMonth=v;renderFinance()};window.ftFinYear=v=>{finYear=Number(v)||new Date().getFullYear();renderFinance()};
function finMetrics(t){return `<div class="grid4"><div class="metric green"><label>Entradas</label><b>${brMoney(t.inn)}</b></div><div class="metric red"><label>Saídas</label><b>${brMoney(t.out)}</b></div><div class="metric"><label>Saldo</label><b>${brMoney(t.bal)}</b></div><div class="metric orange"><label>Pendentes</label><b>${brMoney(t.pend||0)}</b></div></div>`}
function finTable(a){return `<div class="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Paciente</th><th>Valor</th><th>Status</th></tr></thead><tbody>${a.map(f=>`<tr><td>${brDate(f.paidDate||f.dueDate)}</td><td>${E(f.direction)}</td><td>${E(f.description||'')}</td><td>${E(patientById(f.patientId)?.name||'-')}</td><td>${brMoney(f.value)}</td><td>${E(financeStatus(f))}</td></tr>`).join('')||'<tr><td colspan="6">Sem lançamentos.</td></tr>'}</tbody></table></div>`}
function finMonthPage(){let y=Number(finMonth.slice(0,4)),m=Number(finMonth.slice(5)),last=new Date(y,m,0).getDate(),t=period(finMonth+'-01',finMonth+'-'+String(last).padStart(2,'0'));return pageHead('Financeiro','Balanço mensal de entradas e saídas.',`<button class="btn primary" onclick="openFinanceModal()">+ Novo lançamento</button>`)+tabs()+`<div class="toolbar"><input type="month" value="${finMonth}" onchange="ftFinMonth(this.value)"></div>`+finMetrics(t)+`<section class="panel" style="margin-top:13px"><div class="panel-title"><h3>Lançamentos do mês</h3></div>${finTable(t.a)}</section>`}
function finYearPage(){let months=Array.from({length:12},(_,i)=>`${finYear}-${String(i+1).padStart(2,'0')}`),v=months.map(m=>{let last=new Date(finYear,Number(m.slice(5)),0).getDate();return period(m+'-01',m+'-'+String(last).padStart(2,'0'))}),inn=v.reduce((s,x)=>s+x.inn,0),out=v.reduce((s,x)=>s+x.out,0),max=Math.max(1,...v.flatMap(x=>[x.inn,x.out])),all={inn,out,bal:inn-out,pend:v.reduce((s,x)=>s+x.pend,0)};return pageHead('Financeiro','Balanço anual com comparação mês a mês.',`<button class="btn primary" onclick="openFinanceModal()">+ Novo lançamento</button>`)+tabs()+`<div class="toolbar"><input type="number" min="2020" max="2100" value="${finYear}" onchange="ftFinYear(this.value)"></div>`+finMetrics(all)+`<section class="panel" style="margin-top:13px"><div class="panel-title"><h3>Entradas x saídas • ${finYear}</h3></div><div class="ftAnnual">${v.map((x,i)=>`<div class="ftCol"><div class="ftBar" style="height:${Math.max(2,x.inn/max*145)}px" title="Entradas ${brMoney(x.inn)}"></div><div class="ftBar out" style="height:${Math.max(2,x.out/max*145)}px" title="Saídas ${brMoney(x.out)}"></div><span>${new Date(finYear,i,1).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</span></div>`).join('')}</div></section>`}
renderFinance=function(){if(finView==='mes'){document.getElementById('main').innerHTML=finMonthPage();return}if(finView==='ano'){document.getElementById('main').innerHTML=finYearPage();return}old.fin();let h=document.querySelector('#main .page-head');if(h)h.insertAdjacentHTML('afterend',tabs())};window.renderFinance=renderFinance;
window.render=function(){markNav();let fn={dashboard:renderDashboard,agenda:renderAgenda,patients:renderPatients,assessments:renderAssessments,templates:renderTemplates,professionals:renderProfessionals,visits:renderVisits,recurrences:renderRecurrences,finance:renderFinance,categories:renderCategories,ai:renderAI,backup:renderBackup}[currentPage]||renderDashboard;fn();hydrateBrand()};try{render=window.render}catch(e){}
css();modal();console.info('Isabela Martins v24 carregada');
})();
